[book]
authors = ["Tulir Asokan"]
language = "en"
multilingual = false
src = "src"
title = "mautrix-bridges"
site-url = "/bridges/"

[build]
build-dir = "dist"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/tulir/mautrix-docs"
git-repository-icon = "fa-github"
additional-js = ["src/python/bridge-selector.js"]
#no-section-label = true

[output.linkcheck]
optional = true
user-agent = "Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"
cache-timeout = 604800
exclude = [ 'developer\.android\.com' ]
traverse-parent-directories = false
